export const colleges = [
  "AISSMS College of Engineering",
  "Annasaheb Dange College of Engineering and Technology",
  "Atharva College of Engineering",
  "Bharati Vidyapeeth College of Engineering",
  "D. Y. Patil College of Engineering and Technology",
  "Datta Meghe College Of Engineering",
  "Don Bosco Institute of Technology",
  "Dr. Babasaheb Ambedkar Technological University",
  "Fr. Conceicao Rodrigues Institute of Technology",
  "Government College Of Engineering Amravati",
  "Government College of Engineering, Yavatmal",
  "Government Polytechnic Nashik",
  "Government Polytechnic Pune",
  "Government Polytechnic, Tuljapur Road",
  "Jagdambha College Of Engineering & Technology",
  "K.C. College of Engineering & Management Studies & Research",
  "Lokmanya Tilak College Of Engineering",
  "M. H. Saboo Siddik Engineering College",
  "Maharashtra Institute of Technology Aurangabad",
  "M.B.E. Society's College of Engineering",
  "Marathwada Mitra Mandal's College of Engineering",
  "MET Institute of Technology Polytechnic",
  "Navsahyadri Education Society's Group of Institutions",
  "PES Modern College of Engineering",
  "Pravara Rural Education Society's Sir Visvesvaraya Institute of Technology",
  "Pune District Education Association College of Engineering",
  "Rizvi College of Engineering",
  "Sanjay Ghodawat University",
  "Sanjivani College of Engineering",
  "Sant Gadge Baba Amravati University",
  "Savitribai Phule Pune University",
  "Shatabdi College of Engineering and Research",
  "Shivaji S. Jondhale College of Engineering",
  "Shri Guru Gobind Singhji Institute of Engineering and Technology",
  "SKN Sinhgad College of Engineering",
  "Smt. Indira Gandhi College Of Engineering",
  "Smt. Kashibai Navale College of Engineering",
  "SNJB's Late Sau Kantabai Bhavarlalji Jain College of Engineering",
  "Sreyas Institute of Engineering and Technology",
  "St. John College of Engineering and Management",
  "Suryodaya College of Engineering & Technology",
  "Tatyasaheb Kore Institute of Engineering and Technology",
  "Teegala Krishna Reddy Engineering College",
  "Terna Engineering College",
  "Terna Public Charitable Trust's College of Engineering",
  "Thadomal Shahani Engineering College",
  "TPCT's College Of Engineering",
  "Vidyalankar Institute of Technology",
  "Vidyavardhini's College of Engineering and Technology Campus",
  "Vishwakarma Institute of Technology (VIT)",
  "D.Y.Patil College of Engineering & Technology Kasabawad Kolhapur"
]